2025-07-15 14:17:57,943 INFO    MainThread:21581 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /media/HDD/fdittaro/Second_traing_phase/MNV2+UNet++/WE3DS/wandb/run-20250715_141757-7bl8fdrc/logs/debug.log
2025-07-15 14:17:57,943 INFO    MainThread:21581 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /media/HDD/fdittaro/Second_traing_phase/MNV2+UNet++/WE3DS/wandb/run-20250715_141757-7bl8fdrc/logs/debug-internal.log
2025-07-15 14:17:57,944 INFO    MainThread:21581 [wandb_init.py:init():852] calling init triggers
2025-07-15 14:17:57,944 INFO    MainThread:21581 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'epochs': 50, 'batch_size': 64, '_wandb': {}}
2025-07-15 14:19:22,264 WARNING MainThread:21581 [wandb_init.py:init():1654] [no run ID] interrupted
Traceback (most recent call last):
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1650, in init
    return wi.init(run_settings, run_config, run_printer)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 873, in init
    self._wl.finish_all_active_runs()
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 150, in finish_all_active_runs
    run.finish()
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 503, in wrapper
    return func(self, *args, **kwargs)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 451, in wrapper
    return func(self, *args, **kwargs)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in finish
    return self._finish(exit_code)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2330, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2543, in _atexit_cleanup
    self._on_finish()
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2799, in _on_finish
    wait_with_progress(
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 24, in wait_with_progress
    return wait_all_with_progress(
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 87, in wait_all_with_progress
    return asyncio_compat.run(progress_loop_with_timeout)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/lib/asyncio_compat.py", line 30, in run
    return future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 434, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
2025-07-15 14:19:23,064 INFO    MsgRouterThr:21581 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
