2025-08-08 14:58:07,598 INFO    MainThread:32150 [wandb_setup.py:_flush():68] Current SDK version is 0.19.10
2025-08-08 14:58:07,598 INFO    MainThread:32150 [wandb_setup.py:_flush():68] Configure stats pid to 32150
2025-08-08 14:58:07,598 INFO    MainThread:32150 [wandb_setup.py:_flush():68] Loading settings from /home/fdittaro/.config/wandb/settings
2025-08-08 14:58:07,598 INFO    MainThread:32150 [wandb_setup.py:_flush():68] Loading settings from /media/HDD/fdittaro/Third_training_phase/CropAndWeed/wandb/settings
2025-08-08 14:58:07,598 INFO    MainThread:32150 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-08-08 14:58:07,598 INFO    MainThread:32150 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /media/HDD/fdittaro/Third_training_phase/CropAndWeed/wandb/run-20250808_145807-i1rmor2u/logs/debug.log
2025-08-08 14:58:07,598 INFO    MainThread:32150 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /media/HDD/fdittaro/Third_training_phase/CropAndWeed/wandb/run-20250808_145807-i1rmor2u/logs/debug-internal.log
2025-08-08 14:58:07,598 INFO    MainThread:32150 [wandb_init.py:monkeypatch_ipython():643] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd7306a0430>
2025-08-08 14:58:07,598 INFO    MainThread:32150 [wandb_init.py:init():852] calling init triggers
2025-08-08 14:58:07,598 INFO    MainThread:32150 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'epochs': 50, 'batch_size': 32, '_wandb': {}}
2025-08-08 14:58:07,598 INFO    MainThread:32150 [wandb_init.py:init():893] starting backend
2025-08-08 14:58:07,598 INFO    MainThread:32150 [wandb_init.py:init():897] sending inform_init request
2025-08-08 14:58:07,605 INFO    MainThread:32150 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-08-08 14:58:07,605 INFO    MainThread:32150 [wandb_init.py:init():907] backend started and connected
2025-08-08 14:58:07,610 INFO    MainThread:32150 [wandb_run.py:_label_probe_notebook():1369] probe notebook
2025-08-08 14:58:07,610 INFO    MainThread:32150 [wandb_run.py:_label_probe_notebook():1379] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-08-08 14:58:07,610 INFO    MainThread:32150 [wandb_init.py:init():1002] updated telemetry
2025-08-08 14:58:07,612 INFO    MainThread:32150 [wandb_init.py:init():1026] communicating run to backend with 90.0 second timeout
2025-08-08 14:58:08,254 INFO    MainThread:32150 [wandb_init.py:init():1101] starting run threads in backend
2025-08-08 14:58:08,363 INFO    MainThread:32150 [wandb_run.py:_console_start():2566] atexit reg
2025-08-08 14:58:08,364 INFO    MainThread:32150 [wandb_run.py:_redirect():2414] redirect: wrap_raw
2025-08-08 14:58:08,364 INFO    MainThread:32150 [wandb_run.py:_redirect():2483] Wrapping output streams.
2025-08-08 14:58:08,364 INFO    MainThread:32150 [wandb_run.py:_redirect():2506] Redirects installed.
2025-08-08 14:58:08,365 INFO    MainThread:32150 [wandb_init.py:init():1147] run started, returning control to user process
2025-08-08 14:58:08,366 INFO    MainThread:32150 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-08-08 14:58:13,571 INFO    MainThread:32150 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-08-08 14:58:13,571 INFO    MainThread:32150 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-08-08 14:58:13,580 INFO    MainThread:32150 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-08-08 14:58:16,151 INFO    MainThread:32150 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-08-08 14:58:16,151 INFO    MainThread:32150 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-08-08 14:58:16,153 INFO    MainThread:32150 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-08-08 14:58:18,408 INFO    MainThread:32150 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-08-08 14:58:18,408 INFO    MainThread:32150 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-08-08 14:58:18,489 INFO    MainThread:32150 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-08-08 14:58:21,026 INFO    MainThread:32150 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-08-08 14:58:21,026 INFO    MainThread:32150 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-08-08 14:58:53,114 INFO    MainThread:32150 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-08-08 14:59:07,717 INFO    MainThread:32150 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-08-08 14:59:07,717 INFO    MainThread:32150 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-08-08 14:59:07,735 INFO    MainThread:32150 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-08-08 14:59:09,923 INFO    MainThread:32150 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-08-08 14:59:09,923 INFO    MainThread:32150 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-08-08 14:59:09,924 INFO    MainThread:32150 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-08-08 14:59:12,714 INFO    MainThread:32150 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-08-08 14:59:12,714 INFO    MainThread:32150 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-08-08 14:59:12,716 INFO    MainThread:32150 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-08-08 14:59:15,026 INFO    MainThread:32150 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-08-08 14:59:15,027 INFO    MainThread:32150 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-08-08 14:59:17,397 INFO    MainThread:32150 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-08-08 15:01:43,557 INFO    MsgRouterThr:32150 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-08-08 15:01:44,397 ERROR   Thread-2  :32150 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2487, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/media/HDD/fdittaro/env/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
